### PR TITLE
Add plugin: vis-tables

### PR DESCRIPTION
**Pull request by thyssentishman**

### CODE REVIEW

**Comment by erf** [comment]
That's not a git repository?

**Comment by thyssentishman** [comment]
It is, you can clone it using the ssh url below the title

**Comment by erf** [comment]
Aha, you should add the ssh url as the `url`. All the other plugin urls are git repositories that can be cloned. It's easier if you want to copy paste the url and use it in my [vis-plug](https://github.com/erf/vis-plug). I should perhaps have described this better in the `README.md`

**Comment by thyssentishman** [comment]
Ah I see... How would one read about the plugin before deciding to install it though? At least for me, that's very important. I get that it's convenient to have the website URL be the same as the repo like in GitHub, but if that's not the case, wouldn't you rather have the website than the clone URL? Specially because in the website you created it is displayed as a clickable link that should open something, no? 

Just my opinion. Perhaps an additional 'Homepage' link would be useful for these cases. Let me know if you still prefer the clone URL and I'll change it.

**Comment by erf** [comment]
If you change the `url` to the git repo, you can add another field `homepage`, which i can show if it's there. Maybe we later change `url` to `repo` as it's more descriptive. What do you think?

**Comment by thyssentishman** [comment]
I think that's perfect. Thank you very much.

**Pull request merged**
